export const REQUEST_GET_FILMS = "REQUEST_GET_FILMS";
export const SUCCESS_GET_FILMS = "SUCCESS_GET_FILMS";

export const REQUEST_GET_FILM = "REQUEST_GET_FILM";
export const SUCCESS_GET_FILM = "SUCCESS_GET_FILM";

export const ADD_FILM = "ADD_FILM";
export const DELETE_FILM = "DELETE_FILM";
export const EDIT_FILM = "EDIT_FILM";

export const FILTERED_FILMS = "FILTERED_FILMS";

export const TOGGLE_ADD_MODAL = "TOGGLE_ADD_MODAL";
export const TOGGLE_CHECK_MODAL = "TOGGLE_CHECK_MODAL";
export const TOGGLE_EDIT_MODAL = "TOGGLE_EDIT_MODAL";

export const SET_ERROR = "SET_ERROR";
export const RESET_ERROR = "RESET_ERROR";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
